

CREATE TABLE YOKEFOLK (
    YOKE_FOLK_ID INT(10) AUTO_INCREMENT,
    SCHOOL_ID INT(10),
    JOB_TITLE CHAR(15),
    NOTES CHAR(200),
    PRIMARY KEY (YOKE_FOLK_ID)
);

CREATE TABLE SCHOOL (
    SCHOOL_ID INT(10) AUTO_INCREMENT,
    COUNTY_ID INT(10),
    NAME CHAR(35),
    ADDRESS CHAR(100),
    PHONE CHAR(14),
    PRIMARY KEY (SCHOOL_ID)
);

CREATE TABLE COUNTY (
    COUNTY_ID INT(10) AUTO_INCREMENT,
    NAME CHAR(25),
    PRIMARY KEY (COUNTY_ID)
);
    
CREATE TABLE BANQUET (
    BANQUET_ID INT(10) AUTO_INCREMENT,
    YOKE_FOLK_ID INT(10),
    BANQUET_YEAR INT(10),
    PACKET_GIVEN TINYINT(1),
    PACKET_TURNED_IN TINYINT(1),
    NUMBER_LETTERS_DONE INT(100),
    TSHIRT_GIVEN TINYINT(1),
    NOTES CHAR(200),
    PRIMARY KEY (BANQUET_ID)
);

CREATE TABLE APPLICANT (
    APPLICANT_ID INT(10),
    YOKE_FOLK_ID INT(10),
    APPLICATION_DONE DATE,
    INTERVIEW_COMPLETED DATE,
    BACKROUND_CHECK_COMPLETED DATE,
    REFERENCES_SUBMITTED DATE,
    INSURANCE_CARD_SUBMITTED TINYINT(1),
    TRAINING_COMPLETED DATE,
    COMMIT_FORM_SIGNED TINYINT(1),
    PRIMARY KEY (APPLICANT_ID)
);

CREATE TABLE PERSON (
	PERSON_ID INT(10),
	YOKE_FOLK_ID INT(10),
	APPLICANT_ID INT(10),
	LAST_NAME CHAR(25),
    FIRST_NAME CHAR(25),
    ADDRESS CHAR(100),
    CITY CHAR(25),
    EMAIL CHAR(35),
    MOBILE_PHONE CHAR(14),
    HOME_PHONE CHAR(14),
    WORK_PHONE CHAR(14),
    GENDER CHAR(10),
	PRIMARY KEY (PERSON_ID)
);
	
ALTER TABLE PERSON
ADD CONSTRAINT FK_YOKE_FOLK
FOREIGN KEY (YOKE_FOLK_ID)
REFERENCES YOKEFOLK(YOKE_FOLK_ID);

ALTER TABLE PERSON
ADD CONSTRAIN FK_APPLICANT
FOREIGN KEY (APPLICANT_ID)
REFERENCES APPLICANT(APPLICANT_ID);

ALTER TABLE YOKEFOLK
ADD CONSTRAINT FK_SCHOOL_ID
FOREIGN KEY (SCHOOL_ID)
REFERENCES SCHOOL(SCHOOL_ID);

ALTER TABLE SCHOOL 
ADD CONSTRAINT FK_COUNTY_ID
FOREIGN KEY (COUNTY_ID)
REFERENCES COUNTY(COUNTY_ID);

ALTER TABLE BANQUET 
ADD CONSTRAINT FK_YOKE_FOLK_ID
FOREIGN KEY (YOKE_FOLK_ID)
REFERENCES YOKEFOLK(YOKE_FOLK_ID);

ALTER TABLE APPLICANT
ADD CONSTRAINT FK_YOKE_FOLK_ID_APPLICANT
FOREIGN KEY (YOKE_FOLK_ID)
REFERENCES YOKEFOLK(YOKE_FOLK_ID);